# Generated by Django 5.0.4 on 2024-04-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='color_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='color_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diskquantity',
            name='disk_quantity_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diskquantity',
            name='disk_quantity_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processormodel',
            name='processor_model_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processormodel',
            name='processor_model_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramsize',
            name='ram_size_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ramsize',
            name='ram_size_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usetype',
            name='use_type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usetype',
            name='use_type_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
