# Generated by Django 5.0.4 on 2024-04-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETrade', '0002_brand_brand_en_brand_brand_tr_color_color_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='iamge',
            new_name='image',
        ),
    ]
