# Generated by Django 5.0.4 on 2024-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETrade', '0003_rename_iamge_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
            ],
        ),
    ]
