# Generated by Django 5.0.4 on 2024-04-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETrade', '0004_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='product_type_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='product_type_tr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
