# Generated by Django 5.0.4 on 2024-04-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETrade', '0007_alter_product_color_alter_product_disk_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
