# Generated by Django 5.0.4 on 2024-04-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETrade', '0011_profil_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name_plural': 'Profiles'},
        ),
    ]
